<?php

/**
 * @file
 * Provide a list chunk type.
 */

/**
 * Implements hook_chunk_types().
 */
function chunks_list_chunk_types() {
  return array(
    'list' => array(
      'title' => t('List'),
      'default configuration' => array(
        'style' => 'ul',
        'list' => array(''),
      ),
      'default type settings' => array(
        'edit_in_place' => 1,
        'format' => '',
      ),
      'client themeable' => TRUE,
    ),
  );
}
/**
 * Implements hook_CHUNK_TYPE_chunk_type_settings_form().
 */
function chunks_list_list_chunk_type_settings_form($field, $settings) {
  $form = array();

  $form['edit_in_place'] = array(
    '#type' => 'checkbox',
    '#title' => t('Edit list items in-place'),
    '#default_value' => $settings['edit_in_place'],
    '#description' => t('This requires the pen library (https://github.com/sofish/pen).'),
  );

  // Only display this setting to users with 'administer filters' permission
  // since we do not limit the available filters to those which the current user
  // has access to.
  if (user_access('administer filters')) {
    $formats = array();
    foreach (filter_formats() as $id => $format) {
      $formats[$id] = $format->name;
    }

    $form['format'] = array(
      '#type' => 'select',
      '#title' => t('Text format'),
      '#options' => $formats,
      // By default $settings['format'] is an empty string so the default value
      // can be derived from the first value of $formats which should be the
      // global default.
      '#default_value' => !empty($settings['format']) ? $settings['format'] : reset($formats),
    );
  }

  return $form;
}

/**
 * Implements hook_CHUNK_TYPE_chunk_is_allowed().
 */
function chunks_list_list_chunk_is_allowed($settings, $field, $instance, $langcode) {
  $format = filter_format_load($settings['format']);
  if (!filter_access($format)) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Implements hook_CHUNK_TYPE_chunk_form().
 */
function chunks_list_list_chunk_form(&$configuration, $settings, $form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $config_form = array();

  $config_form['style'] = array(
    '#type' => 'select',
    '#title' => t('Style'),
    '#default_value' => $configuration['style'],
    '#options' => array(
      'ul' => t('Bulleted'),
      'ol' => t('Numbered'),
    ),
  );

  $config_form['list'] = array(
    '#type' => 'textarea',
    '#default_value' => $configuration['list'],
    '#value_callback' => 'chunks_list_text_to_items',
    '#after_build' => array('chunks_list_items_to_text'),
    '#format' => $settings['format'],
  );

  if ($settings['edit_in_place']) {

    // Hide list textarea
    $config_form['list']['#attributes'] = array(
      'style' => 'display: none;',
    );

    $config_form['inplace_items'] = array(
      '#markup' => '<' . $configuration['style'] . ' contenteditable>',
    );

    foreach ($configuration['list'] as $key => $list_item) {
      $config_form['inplace_items']['#markup'] .= '<li>' . $list_item . '</li>';
    }

    $config_form['inplace_items']['#markup'] .= '</' . $configuration['style'] . '>';

    $config_form['items']['#attached'] = array(
      'js' => array(
        drupal_get_path('module', 'chunks_list') . '/chunks-list.js',
      ),
      'library' => array(
        array('chunks', 'pen'),
      ),
    );
  }

  if ($settings['preview_on_client']) {
    $config_form['#attached'] = array(
      'js' => array(
        drupal_get_path('module', 'chunks_list'). '/chunks-list.js',
      ),
    );
  }

  return $config_form;
}

/**
 * #value_callback for the "list" textarea.
 *
 * Breaks one string into an array of list items.
 */
function chunks_list_text_to_items($element, $input = FALSE, $form_state) {
  $return = $input !== FALSE ? $input : $element['#default_value'];
  if (is_string($return)) {
    $return = explode("\n", $return);
  }
  foreach ($return as $key => $list_item) {
    $return[$key] = str_replace("\n", "", $list_item);
    $return[$key] = str_replace("\r", "", $list_item);
  }
  return $return;
}

/**
 * #after_build handler for the "list" textarea.
 *
 * Turns an array of items back to text.
 */
function chunks_list_items_to_text($element) {
  $element['#default_value'] = implode("\n", $element['#default_value']);
  $element['#value'] = implode("\n", $element['#value']);
  return $element;
}

/**
 * Implements hook_CHUNK_TYPE_chunk_form_validate().
 */
function chunks_list_list_chunk_form_validate($configuration, &$form_state, $form) {
  // This should never happen because the chunk type should not be displayed to
  // users who do not have access to the filter format. Still, let's be safe.
  $format = filter_format_load($configuration['list']['#format']);

  if (!filter_access($format)) {
    form_error($configuration['list'], t('You do not have permission to use the %format text format, which this instance of the list chunk type requires.', array('%format' => $format->format)));
    return FALSE;
  }
  return TRUE;
}

/**
 * Implements hook_CHUNK_TYPE_chunk_is_empty().
 */
function chunks_list_list_chunk_is_empty($configuration, $item, $field) {
  // If any list item contains data, this chunk is not empty.
  foreach ($configuration['list'] as $item) {
    if (!empty($item)) {
      return FALSE;
    }
  }
  return TRUE;
}

/**
 * Implements hook_CHUNK_TYPE_chunk_presave().
 */
function chunks_list_list_chunk_presave(&$item) {
  // Don't save any empty list items.
  $list_items = $item['data']['configuration']['list'];
  foreach ($list_items as $key => $list_item) {
    if (empty($list_item)) {
      unset($item['data']['configuration']['items'][$key]);
    }
  }
}

/**
 * Implements hook_preprocess_chunk().
 */
function chunks_list_preprocess_chunk(&$variables) {
  if ($variables['chunk_type']->name == 'list') {

    $config = $variables['configuration'];

    // Do not show empty list items.
    foreach ($config['list'] as $key => $item) {
      if (empty($item)) {
        unset($variables['configuration']['list'][$key]);
      }
    }
  }
}
