<?php

/**
 * @file
 * Default chunk template.
 *
 * Should never actually be used since each chunk should provide it's own
 * template.
 *
 * Available variables:
 * - $classes: The string value for the class attribute initially generated by
 *   template_preprocess().
 * - $configuration: The associative array representing the chunk's
 *   configuration.
 * - $type_settings: An associative array representing the chunk type settings
 *   connected to the chunk field's instance.
 * - $chunk_type: The ChunkType object representing the chunk's type.
 * - $entity: If we are viewing an entity, this will be the entity object.
 *   Otherwise it will be FALSE.
 * - $entity_type: If we are viewing an entity, this will be the string
 *   represnting the entity's type. Otherwise it will be FALSE.
 *
 * @see template_preprocess()
 * @see template_preprocess_chunk()
 *
 * @ingroup themeable
 */
?>

<div class="<?php print $classes; ?>">
  This is the default chunk template. If you you're seeing this, the <em><?php print $chunk_type->module; ?></em> module has not provided a template file for the <em><?php print $chunk_type->name; ?></em> chunk type.
</div>

