<?php

/**
 * @file
 * Default chunk template.
 *
 * Should never actually be used since each chunk should provide it's own
 * template.
 *
 * Available variables:
 * - $classes: The string value for the class attribute initially generated by
 *   template_preprocess().
 * - $configuration: The associative array representing the chunk's
 *   configuration.
 * - $chunk_type: The ChunkType object representing the chunk's type.
 *
 * @see template_preprocess()
 * @see template_preprocess_chunk()
 *
 * @ingroup themeable
 */
?>

<div class="<?php print $classes; ?>">
  This is the default chunk template. If you you're seeing this, the <em><?php print $chunk_type->module; ?></em> module has not provided a template file for the <em><?php print $chunk_type->name; ?></em> chunk type.
</div>

