<?php

/**
 * @file
 * Chunk template for the entity reference chunk type.
 *
 * Available variables:
 * - $classes: The string value for the class attribute initially generated by
 *   template_preprocess().
 * - $configuration: The associative array representing the chunk's
 *   configuration.
 * - $referenced_entity_view: The rendereable array representing the referenced
 *   entity to display.
 * - $referenced_entity: The rendered referenced entity.
 * - $instance_settings: An associative array representing the chunk instance
 *   settings
 *   connected to the chunk field's instance.
 * - $chunk_type: The ChunkType object representing the chunk's type.
 * - $entity: If we are viewing an entity, this will be the entity object.
 *   Otherwise it will be FALSE.
 * - $entity_type: If we are viewing an entity, this will be the string
 *   represnting the entity's type. Otherwise it will be FALSE.
 * - $field_name: The field name for the parent chunks field.
 * - $langcode: The language code for the parent chunks field.
 * - $delta: The delta for the current chunk within the parent chunks field.
 *
 * @see template_preprocess()
 * @see template_preprocess_chunk()
 * @see chunks_entity_reference_preprocess_chunk()
 *
 * @ingroup themeable
 */
?>

<?php if (!empty($reference_entity_view) || $preview): ?>
  <div class="<?php print $classes; ?>"><?php print $referenced_entity; ?></div>
<?php endif; ?>
