<?php

/**
 * @file
 * Chunk template for the heading chunk type.
 *
 * Available variables:
 * - $classes: The string value for the class attribute initially generated by
 *   template_preprocess().
 * - $configuration: The associative array representing the chunk's
 *   configuration.
 *   -  text: A string of text with which to fill the heading.
 *   -  level: An integer representing the header level (2, 3, 4, 5, or 6).
 * - $chunk_type: The ChunkType object representing the chunk's type.
 *
 * @see template_preprocess()
 * @see template_preprocess_chunk()
 *
 * @ingroup themeable
 */
?>

<h<?php print $configuration['level']; ?> class="<?php print $classes; ?>" <?php if (isset($configuration['id'])): ?>id="<?php print $configuration['id']; ?>"<?php endif; ?>><?php print check_plain($configuration['text']); ?></h<?php print $configuration['level']; ?>>
