<?php

/**
 * @file
 * Chunk template for the text chunk type.
 *
 * Available variables:
 * - $classes: The string value for the class attribute initially generated by
 *   template_preprocess().
 * - $configuration: The associative array representing the chunk's
 *   configuration.
 * - $chunk_type: The ChunkType object representing the chunk's type.
 *
 * @see template_preprocess()
 * @see template_preprocess_chunk()
 *
 * @ingroup themeable
 */
?>

<div class="<?php print $classes; ?>">
  <?php print check_plain($configuration['text']); ?>
</div>

