<?php

/**
 * @file
 * Quote chunk template.
 *
 * Available variables:
 * - $classes: The string value for the class attribute initially generated by
 *   template_preprocess().
 * - $configuration: The associative array representing the chunk's
 *   configuration.
 *   - quote: A string containing markup which makes up the quotation.
 *   - attribution: A string containing markup which makes up the <cite>
 *     element.
 *   - attribution_location: A string containing a URL which serves as the
 *     quotation source.
 *   - edit_in_place: A boolean indicating whether or not this chunk is being
 *     edited in place.
 * - $cite_attribute: A string containing the cite="" attribute or an empty
 *   string depending on whether the attribution_location configuration value is
 *   empty.
 * - $instance_settings: An associative array representing the chunk instance
 *   settings
 *   connected to the chunk field's instance.
 * - $chunk_type: The ChunkType object representing the chunk's type.
 * - $entity: If we are viewing an entity, this will be the entity object.
 *   Otherwise it will be FALSE.
 * - $entity_type: If we are viewing an entity, this will be the string
 *   represnting the entity's type. Otherwise it will be FALSE.
 * - $field_name: The field name for the parent chunks field.
 * - $langcode: The language code for the parent chunks field.
 * - $delta: The delta for the current chunk within the parent chunks field.
 * - $preview: A boolean indicating whether or not the chunk is being previewed.
 *
 * @see template_preprocess()
 * @see template_preprocess_chunk()
 * @see chunks_quote_preprocess_chunk()
 *
 * @ingroup themeable
 */

?>

<blockquote class="<?php print $classes; ?>"<?php print $cite_attribute; ?>>
  <p<?php if (isset($configuration['edit_in_place'])): ?> contenteditable<?php endif; ?>>
    <?php print filter_xss(trim(preg_replace('/(\s|<br>|<\/?div>)+/', ' ', $configuration['quote'])), array('a', 'b', 'em', 'i', 'strong', 'u')); ?>
  </p>
  <?php if (!empty($configuration['attribution'])): ?>
    <footer>
      <cite<?php if (isset($configuration['edit_in_place'])): ?> contenteditable<?php endif; ?>><?php print filter_xss(trim(preg_replace('/(\s|<br>|<\/?div>)+/', ' ', $configuration['attribution'])), array('a', 'b', 'em', 'i', 'strong', 'u')); ?></cite>
    </footer>
  <?php endif; ?>
</blockquote>
